apiVersion: "poc.autoscaling.k8s.io/v1alpha1"
kind: VerticalPodAutoscaler
metadata:
  name: pdb-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: pdb-controller
  updatePolicy:
    updateMode: "Auto"
