apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
  labels:
    application: external-dns
    version: v0.3.0-alpha.4
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: external-dns
  template:
    metadata:
      labels:
        application: external-dns
        version: v0.3.0-alpha.4
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        iam.amazonaws.com/role: "{{ .LocalID }}-app-external-dns"
    spec:
      tolerations:
       - key: CriticalAddonsOnly
         operator: Exists
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.3.0-alpha.4
        args:
        - --in-cluster
        - --source=service
        - --source=ingress
        - --provider=aws
        - --registry=txt
        - --record-owner-id={{ .Region }}:{{ .LocalID }}
        - --dry-run=false
        - --debug
        - --domain=
        - --zone=""
        - --compatibility # change this to string later to --compatibility=mate, when this flag value will become a string type
        - --policy=upsert-only # remove when we are sure external-dns can be trusted
      - name: external-dns-migration
        image: pierone.stups.zalan.do/teapot/external-dns-migration:v0.1.2
        args:
        - --source-txt-label=mate:{{ .LocalID }}
        - --target-txt-label=heritage=external-dns,external-dns/owner={{ .Region }}:{{ .LocalID }}
      imagePullSecrets:
        - name: pierone.stups.zalan.do
