# example: remove the app-ingress-controller deployment from kube-system
# pre_apply:
# - name: app-ingress-controller
#   namespace: kube-system
#   kind: deployment

pre_apply: # everything defined under here will be deleted before applying the manifests
- name: kube-dns
  namespace: kube-system
  kind: deployment
- name: kube-dns-autoscaler
  namespace: kube-system
  kind: deployment
- name: kube-dns
  namespace: kube-system
  kind: service
post_apply: [] # everything defined under here will be deleted after applying the manifests
